### ISSUE TITLE
Axis title and labels easily overlap for TH2 plots.

### ISSUE THREAD

**Issue by xzf89718** [joeycarter/atlas-plots#5]
![Run2_ggf1_4J12_normalize_OR4J12](https://user-images.githubusercontent.com/58804221/134366312-f4286bd9-e274-4dfe-9545-f8fd1e7b053e.png)
![Run2_ggf1_4J12_normalize_OR4J12](https://user-images.githubusercontent.com/58804221/134366536-cbc8d000-0786-4412-9ff4-df491643abae.png)
Hi, Joey! Here're two plots I made, I add margin and use hist2d.GetZaxis().SetTitleOffset(1.6) to plot the second one, the first one just use aplt.set_atlas_style() and them refer to this example: https://atlas-plots.readthedocs.io/en/latest/examples.html.  
I try a solution for root_helpers: https://github.com/joeycarter/atlas-plots/compare/master...xzf89718:zifeng?expand=1 but I'm sure this solution is not matplotlib like and need familiar with plain ROOT. I'm pleased to hear your ideas on it. Here're the codes how I made this plots: https://gitlab.cern.ch/zifeng/triggerInventor/-/blob/zifeng/plotEffi.py#L134  
Cheers,  
Zifeng

**Comment by joeycarter** [comment]
Hi Zifeng,

Thanks for the feedback. I agree, having to call ROOT functions like `hist.GetXaxis().SetTitleOffset()` and `ax.pad.SetMargin()` go against the goal of providing a matplotlib-like interface.

For setting the title offset, the most similar function in matplotlib is [Axes.set_xlabel()](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html) using the `labelpad` option. I don't want to use this nomenclature with atlasplots since it clashes with the usual meaning of "pad" (i.e. a ROOT `TPad`). Instead, I like the idea you proposed of providing the appropriate calls in `aplt.root_helpers` and accessing them in the call to `ax.set_xlabel()`. Now, these attributes can be set with, for example:

```python
ax.set_xlabel("X", titleoffset=1.6, titlecolor="red")
```

This is not exactly matplotlib syntax, but it's in the same spirit while still using familiar ROOT nomenclature. I have created a new helper function in `aplt.root_helpers` to do this (`set_axis_attributes`) since these functions only apply to `TAxis` objects, and not a generic data object (histograms, graphs, etc.) that inherits from the ROOT graphic-attributes classes (`TAttLine`, `TAttFill`, `TAttMarker`, etc).

For the pad margins, I've added the function `ax.set_pad_margins()`. Now, instead of calling, for example `ax.pad.SetRightMargin(0.2)`, you can do:

```python
ax.set_pad_margins(right=0.2)
```

Let me know if you have any concerns with these methods. If not, I can close this issue and create a new tag.

Cheers,
Joey

**Comment by xzf89718** [comment]
Thanks, very interesting and useful update! I agree this would be a good way to handle these interfaces. I have no further concerns about it ：）

**Comment by joeycarter** [comment]
Great! I've created tag v0.1.8 (833599b) for this update; I'll close this issue.
